# WORKER_COUNT=1 HOST_UID=$(id -u) docker-compose -f ./docker/docker-compose-standard_worker.yaml -p neurophotonics_standard up -d
# WORKER_COUNT=1 HOST_UID=$(id -u) docker-compose -f ./docker/docker-compose-standard_worker.yaml -p neurophotonics_standard up --build -d
# docker-compose -f ./docker/docker-compose-standard_worker.yaml -p neurophotonics_standard down
# Build this image from neurophotonics level on your local machine
version: '2.4'
services:
  standard_worker:
    build:
      # only necessary if rebuilding image
      context: ../
      dockerfile: ./docker/standard_worker.Dockerfile
    image: registry.vathes.com/sciops/neurophotonics:v0.0.1
    env_file: dev.env
    environment:
      - NEW_USER=datajoint
      - DISPLAY
    user: ${HOST_UID}:anaconda
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../setup.py:/main/setup.py
      - ../requirements.txt:/main/requirements.txt
      - ../README.md:/main/README.md
      - ../scripts:/main/scripts
      - ../neurophotonics:/main/neurophotonics
      - ../workdir:/main/workdir
    scale: ${WORKER_COUNT:-1}
    command:
      - /bin/bash
      - -c
      - |
        set -e
        echo "Running standard_worker..."
        run_workflow standard_worker
